#!/bin/bash

env GOOS=windows GOARCH=amd64 go build -o bin/interface.win.x64.exe
env GOOS=linux GOARCH=amd64 go build -o bin/interface.linux.x64
env GOOS=darwin GOARCH=amd64 go build -o bin/interface.osx.x64

